analysis/urls.py
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [
    path('', views.index, name='index')
]

core/api/urls.py
from django.urls import path, include

from .views import CreateUserView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path("user/register/", CreateUserView.as_view(), name="register"),
    path("token/", TokenObtainPairView.as_view(), name="get_token"),
    path("token/refresh/", TokenRefreshView.as_view(), name="refresh"),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name = 'signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form = LoginForm), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

data_handler/urls.py
from django.urls import path
from .views import upload_zip, delete_data, clean_duplicates

app_name='data_handler'

urlpatterns = [
    path('upload/', upload_zip, name='upload'),
    path('delete/', delete_data, name='delete'),
    path('clean/', clean_duplicates, name='clean')
]

messengeranalyzer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('data/', include('data_handler.urls')),
    path('analysis/', include('analysis.urls')),
    path('api/', include('messengeranalyzer.api.urls')),
    path("api-auth/", include("rest_framework.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=256)
    body = models.TextField()

    def __str__(self):
        return f'Post: {self.title}'

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder' : 'Your usename',
		'class' : 'w-full py-4 px-6 rounded-xl'
    }))        
    email = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder' : 'Your e-mail address',
		'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder' : 'Your password',
		'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder' : 'Repeat password',
		'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
		'placeholder' : 'Your username',
		'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
		'placeholder' : 'Your password',
		'class' : 'w-full py-4 px-6 rounded-xl'
    }))

core/api/views.py
from rest_framework.viewsets import ModelViewSet
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated, AllowAny
from ..models import Post
from .serializers import PostSerializer, UserSerializer
from django.contrib.auth.models import User 


# Simple
class PostViewSet(ModelViewSet):
    queryset = Post.objects.all()
    serializer = PostSerializer

# Enables more cusotmization
class MyView(APIView):
    serializer_class = PostSerializer
    def get(self, request):
        output = [{"title" : output.title, "body" : output.body}
                  for output in Post.objects.all()]
        return Response(output)
    
    def post(self, request):
        serializer = PostSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(serializer.data)
        
class CreateUserView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [AllowAny]

core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm

def index(request):
    return render(request, 'core/index.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form' : form
    })

core/templates/core/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            .spinner {
                display: none;
                width: 50px;
                height: 50px;
                border: 8px solid #f3f3f3;
                border-top: 8px solid #3498db;
                border-radius: 50%;
                animation: spin 2s linear infinite;
                position: absolute;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
            }
    
            @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
            }
        </style>
        <script>
            function showSpinner() {
                document.getElementById('spinner').style.display = 'block';
            }
        </script>
        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Messenger Analyzer</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}" >
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Messenger Analyzer</a>

            
            <div class="space-x-6">
                {% if user.is_authenticated %}
                <a href="{% url 'data_handler:upload' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Upload Data</a>
                {% comment %} <a href="{% url 'data_handler:clean' %}" class="px-6 py-3 text-lg font-semibold bg-blue-300 text-white rounded-xl hover:bg-blue-500">Clean Data</a> {% endcomment %}
                <a href="{% url 'data_handler:delete' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Delete Data</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Logout</a>
                {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-3xl text-center">Analyze your Messenger conversations!</h2>

        <div class="flex items-center justify-center">
            <a href="{% url 'analysis:index' %}" class="px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Analyze</a>
        </div>

        <div class="mt-12">
            {% include "core/info.html" %}
        </div>
    </div>

{% endblock %}

core/templates/core/info.html
{% load static %}
<div class="content-center text-center items-center justify-center">  
  <div>
    <h2 id="how-to-download-facebook-messages-data" class="text-3xl font-semibold">How to download Facebook Messages Data</h2>
    <div class="mt-6">
      <p>
        Visit <a href="https://accountscenter.facebook.com/info_and_permissions/dyi" target="_blank" class="text-blue-500">https://accountscenter.facebook.com/info_and_permissions/dyi</a> and log in to your Facebook account if required. Click "Download or transfer information" then "Specific types of information"
      </p>
      <div class="flex justify-center items-center pt-2 space-x-4">
        <img src="{% static 'img/dlfb1.JPG' %}" alt="alt text" class="h-96" />
        <img src="{% static 'img/dlfb2.JPG' %}" alt="alt text" class="h-96" />
      </div>
    </div>
    <div class="mt-6">
      <p>
        In the next screen, only check the "Messages" box and click "Next". Then select "Download to device" and click "Next" again.    
      </p>
      <div class="flex justify-center items-center pt-2 space-x-4">
        <img src="{% static 'img/dlfb3.JPG' %}" alt="alt text" class="h-96"/>
        <img src="{% static 'img/dlfb4.JPG' %}" alt="alt text" class="h-96"/>
      </div>
    </div>
    <div class="mt-6">
      <p>
        Choose your date range, enter the e-mail address you wish to be notified at, set the format to JSON, and set the media quality to low (allows for fast download as we don&#39;t access the media files).
      </p>
      <div class="flex justify-center items-center pt-2">
        <img src="{% static 'img/dlfb5.JPG' %}" alt="alt text" class="h-96"/>
      </div>
      <p>
        After the download is ready, you will be notified. Download the zip file. The data is now ready to be fed to the program!
      </p>
    </div>
  </div>


  <div class="mt-12">
    <h2 id="available-visualizations" class="text-3xl font-semibold">Available Visualizations</h2>
    <h3 id="top-10-n-most-messaged" class="mt-6 text-xl">Top 10 (n) Most Messaged</h3>
    <p>
      Identifies who you have exchanged the most messages with
    </p>
    <div class="flex justify-center items-center pt-2 space-x-4">
      <img src="{% static 'img/topn.png' %}" alt="alt text" />
    </div>
    <h3 id="messages-over-time-sent-and-received-" class="mt-6 text-xl">Messages over time (sent and received)</h3>
    <p>
      Shows activity over time. May be able to identify cyclical patterns or trends. Can also see the effect of certain events on your messaging habits (e.g. Do I talk to more people during a global pandemic?)
    </p>
    <div class="flex justify-center items-center pt-2 space-x-4">
      <img src="{% static 'img/msg_v_time.PNG' %}" alt="alt text" />
    </div>
    <h3 id="messages-over-time-with-a-specific-contact-sent-and-received-" class="mt-6 text-xl">Messages over time with a specific contact (sent and received)</h3>
    <p>
      Similar to above.
    </p>
    <div class="flex justify-center items-center pt-2 space-x-4">
      <img src="{% static 'img/msg_v_time_contact.png' %}" alt="alt text" />
    </div>
    <h3 id="hourly-distribution-of-sent-messages" class="mt-6 text-xl">Hourly Distribution of sent messages</h3>
    <p>
      Provides information on when you are most likely to reply. Can be used to identify unhealthy patterns or habits.
    </p>
    <div class="flex justify-center items-center pt-2 space-x-4">
      <img src="{% static 'img/msg_dist.JPG' %}" alt="alt text" />
    </div>
    <h3 id="word-spectrum" class="mt-6 text-xl">Word spectrum</h3>
    <p>
      For a specific contact, identify which words you are more likely to type opposed to your contact.
    </p>
    <div class="flex justify-center items-center pt-2 space-x-4">
      <img src="{% static 'img/wordspectrum.PNG' %}" alt="alt text" />
    </div>
  </div>
  
</div>

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}